import {useState, useEffect} from 'react'

import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

export default function Home() {
  return (
    <div>
      <Head>
        <title>KeyboardCat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* Component to load after button push here */}
      <main>
      <Container maxWidth="md">
          <Box
            sx={{
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h3" align="center" paragraph>
              Typing game
            </Typography>
            <Typography variant="h5" align="center"gutterBottom>
              Instructions:
            </Typography>
            <List>
                <ListItem>
                  <ListItemText primary="Rule 1"/>
                </ListItem>
                <ListItem>
                  <ListItemText primary="Rule 2"/>
                </ListItem>
                <ListItem>
                  <ListItemText primary="Rule 3"/>
                </ListItem>
            </List>
            <Box
             display="flex"
             justifyContent="center"
            >
              <Button variant="outlined" color="secondary">
                Start Game
              </Button>

            </Box>
          </Box>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
